@echo off 
cd /d "C:\claude cowork\01_projects\Anal_reports\scripts" 
echo [1/3] 리포트 크롤러 실행 중... 
python crawler.py 
echo [2/3] 경제 캘린더 수집 중... 
python calendar_fetcher.py 
echo [3/4] 매크로 지표 수집 중... 
python macro_fetcher.py 
echo [4/4] 통합 데이터 갱신 중... 
python updater.py 
exit 
